<b> Python Arrays <b>

In [1]:
import array 
my_array = array.array('i',[1,2,3,4])

In [2]:
type(my_array) 

array.array

<b> NumPy arrays <b>

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
#0D array (scalar)

zerod_array = np.array(50)
type(zerod_array)


numpy.ndarray

In [8]:
#1d array 

oned_array = np.array([1,2,7,9,3])

In [9]:
type(oned_array)

numpy.ndarray

In [11]:
#2d array 

twod_array = np.array([[1,2,3],[4,5,6]])

In [12]:
print(twod_array)

[[1 2 3]
 [4 5 6]]


In [13]:
type(twod_array)

numpy.ndarray

In [14]:
int_list = [1,3,5,8]
my_int_array = np.array(int_list)
my_int_array

array([1, 3, 5, 8])

In [16]:
fl_list = [1.1,2.3,4.6]
my_float_arr = np.array(fl_list)
my_float_arr

array([1.1, 2.3, 4.6])

In [19]:
mixed_ele = [1,1.1,2.4,5.7,'hello',True]
my_mix_arr = np.array(mixed_ele)
my_mix_arr

array(['1', '1.1', '2.4', '5.7', 'hello', 'True'], dtype='<U32')

In [20]:
backtolist = my_mix_arr.tolist()
backtolist

['1', '1.1', '2.4', '5.7', 'hello', 'True']

<b> Properties of NumPy <b>

In [21]:
my_int_array

array([1, 3, 5, 8])

In [22]:
type(my_int_array)

numpy.ndarray

In [23]:
my_int_array.dtype

dtype('int32')

In [24]:
my_int_array.ndim

1

In [25]:
my_int_array.shape

(4,)

In [26]:
my_int_array.size

4

<b> Prepopulated arrays <b> 

In [27]:
zeros = np.zeros(6)

In [28]:
zeros

array([0., 0., 0., 0., 0., 0.])

In [29]:
zeros_ints = np.zeros(6, dtype=int)
zeros_ints

array([0, 0, 0, 0, 0, 0])

In [30]:
ones = np.ones(3)


In [31]:
ones

array([1., 1., 1.])

In [32]:
np.empty(10)

array([2.56761491e-312, 2.22809558e-312, 2.46151512e-312, 2.05833592e-312,
       2.41907520e-312, 2.56761491e-312, 2.12199579e-312, 2.56761491e-312,
       2.14321575e-312, 8.34446411e-308])

In [33]:
arange_array = np.arange(1,10)

In [34]:
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1 = np.arange(5,50,3)
a1

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

<b> 2D np array <b> 

In [37]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

two_d_array = np.array([l1,l2,l3])
two_d_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
two_d_array.dtype

dtype('int32')

In [39]:
two_d_array.ndim

2

In [40]:
two_d_array.shape


(3, 3)

In [41]:
two_d_array.size

9

<b> NumPy Computations <b> 

In [42]:
l1 = [1,2,3,4,5]
a1=np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [43]:
l2 = [[1,2,3],[4,5,6]]
a2=np.array(l2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> ways to access array ele <b> 

In [44]:
a1

array([1, 2, 3, 4, 5])

In [46]:
a1[3]

4

In [48]:
a1[-2]

4

In [49]:
a1

array([1, 2, 3, 4, 5])

In [50]:
a1[3] = 4444
a1

array([   1,    2,    3, 4444,    5])

In [51]:
a1[:2]

array([1, 2])

In [52]:
a1[3:]

array([4444,    5])

In [53]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a2[0,0]

1

In [55]:
a2[0,1]

2

In [56]:
a2[1,1]

5

In [57]:
a1

array([   1,    2,    3, 4444,    5])

In [58]:
a_sub = a1[:3]
a_sub

array([1, 2, 3])

In [59]:
type(a_sub)

numpy.ndarray

In [60]:
a_sub

array([1, 2, 3])

In [61]:
a_sub[0] = 100
a_sub

array([100,   2,   3])

In [62]:
a1

array([ 100,    2,    3, 4444,    5])

In [63]:
a_copy = a1.copy()
a_copy

array([ 100,    2,    3, 4444,    5])

In [64]:
a_copy[0] = 50
a_copy

array([  50,    2,    3, 4444,    5])

In [65]:
a1

array([ 100,    2,    3, 4444,    5])

In [66]:
id(a1)

1737565918992

In [67]:
id(a_copy)

1737565921072

<b> Reshaping <b> 

In [68]:
one_Arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
one_Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
two_arr = one_Arr.reshape(4,3)
print(two_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
two_array = one_Arr.reshape(3,4)
print(two_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
two_array.ndim

2

In [72]:
a1

array([ 100,    2,    3, 4444,    5])

In [73]:
sum(a1)

4554

In [74]:
np.sum(a1)


4554

In [ ]:
# try
# 1. create a numpy array with 10000 random elements 
# 2. use sum() and np.sum() and also use %timeit

In [75]:
a1 + 5

array([ 105,    7,    8, 4449,   10])

In [76]:
a1 ** 2

array([   10000,        4,        9, 19749136,       25], dtype=int32)

In [77]:
a1 * 2

array([ 200,    4,    6, 8888,   10])

In [78]:
np.power(a1,3)

array([   1000000,          8,         27, 1865814464,        125],
      dtype=int32)

In [79]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
a2 + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [81]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [82]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.sum(a2,axis=1)

array([ 6, 15])

In [84]:
a1 == 5 # Search !!! 

array([False, False, False, False,  True])

In [85]:
a1

array([ 100,    2,    3, 4444,    5])

In [86]:
a1 > 5 

array([ True, False, False,  True, False])

In [87]:
a1 !=5

array([ True,  True,  True,  True, False])

In [88]:
np.all(a1 < 5000)

True

In [89]:
np.any(a1 < 5000)

True

In [90]:
np.any(a1 > 5000)

False

In [91]:
a1.min()

2

In [92]:
a1.max()

4444

In [93]:
a1.mean()

910.8

In [94]:
a1.std()

1766.9969326515538

In [95]:
a1.var()

3122278.1599999997

In [96]:
np.any((a1 > 5) & (a1 < 10))

False

In [97]:
a1 == a2 

<ipython-input-97-1743c4b6f07c>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1 == a2


False

In [98]:
#Fruit seller sold 20 mangoes and 10 oranges on Friday for a total of 
#Rs. 350. He sold 17 mangoes and 22 oranges for Rs. 500 on saturday.
#Price of fruits dint change both days. What's the price of 1 mango and 1 orange ?

In [100]:
# 20x + 10y = 350 
# 17x + 22y = 500

A=np.array([[20,10],[17,22]])
B=np.array([350,500])

In [101]:
X=np.linalg.solve(A,B)
print(X)

[10. 15.]


In [104]:
X = np.eye(2)

In [105]:
X

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Explore 1!!